### ISSUE TITLE
报错：runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by soldivelot** [ZHO-ZHO-ZHO/ComfyUI-DepthFM#2]
在执行modelloader时会报下面错误：

```
Error occurred when executing DepthFM_ModelLoader_Zho:

runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

  File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\DepthFM.py", line 36, in load_model
    model = DepthFM(depthfm_path)
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 21, in __init__
    self.vae = AutoencoderKL.from_pretrained(vae_id, subfolder="vae")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 569, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 402, in load_config
    raise EnvironmentError(
```

**Comment by wy011745** [comment]
> 在执行modelloader时会报下面错误：
> 
> ```
> Error occurred when executing DepthFM_ModelLoader_Zho:
> 
> runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.
> 
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\DepthFM.py", line 36, in load_model
>     model = DepthFM(depthfm_path)
>             ^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 21, in __init__
>     self.vae = AutoencoderKL.from_pretrained(vae_id, subfolder="vae")
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 569, in from_pretrained
>     config, unused_kwargs, commit_hash = cls.load_config(
>                                          ^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 402, in load_config
>     raise EnvironmentError(
> ```

您好，我也遇到了同样的问题，想请问您是如何解决这个问题的？

**Comment by wy011745** [comment]
> 在执行modelloader时会报下面错误：
> 
> ```
> Error occurred when executing DepthFM_ModelLoader_Zho:
> 
> runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.
> 
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\DepthFM.py", line 36, in load_model
>     model = DepthFM(depthfm_path)
>             ^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 21, in __init__
>     self.vae = AutoencoderKL.from_pretrained(vae_id, subfolder="vae")
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 569, in from_pretrained
>     config, unused_kwargs, commit_hash = cls.load_config(
>                                          ^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "E:\Program Files\Media\ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 402, in load_config
>     raise EnvironmentError(
> ```

您好，我也遇到了同样的问题，想请问您是如何解决这个问题的？
